# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  name: 'PHX-Games'

parameters:
  - name: InstallRust
    type: boolean
    displayName: 'Install Rust'
    default: false
  - name: InstallUMod
    type: boolean
    displayName: 'Install uMod / Oxide'
    default: false


steps:
- powershell: |
   $ServerServiceNames = @("RustUMod")

   $ServerServiceNames | %{ Stop-Service -Name $_}
  displayName: 'Stop Rust Server'
  condition: or(eq(${{ parameters.InstallRust }}, true), eq(${{ parameters.InstallUMod }}, true))

- task: PowerShell@2
  displayName: 'Install / Update Rust Server'
  inputs:
    targetType: filePath
    filePath: '$(System.DefaultWorkingDirectory)/.scripts/Update-BaseRustServer.ps1'
  condition: and(succeeded(), eq(${{ parameters.InstallRust }}, true))

- task: PowerShell@2
  displayName: 'Install UMod'
  inputs:
    targetType: filePath
    filePath: '$(System.DefaultWorkingDirectory)/.scripts/Install-RustOxide.ps1'
  condition: and(succeeded(), eq(${{ parameters.InstallUMod }}, true))
