# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Year:YYYY).$(Month).$(DayOfMonth)$(Rev:.rr)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Server/*

pool:
  name: 'PHX-Games'

variables:
  ScriptsBasePath: '$(System.DefaultWorkingDirectory)/.scripts'
  ServersBasePath: '$(System.DefaultWorkingDirectory)/Server'

stages:
- stage:
  displayName: 'Snapshot Config & Deploy Latest Server Bits (Optional)'
  jobs:
    - job: CCS
      pool: PHX-Games
      displayName: Capture Config Snapshot
      steps:
        - task: PublishBuildArtifacts@1
          displayName: Publish Scripts
          inputs:
            ArtifactName: Scripts
            PathtoPublish: $(Build.SourcesDirectory)/.scripts
            publishLocation: Container
        - task: PublishBuildArtifacts@1
          displayName: Publish Configuration Snapshot As Build Artifact
          inputs:
            ArtifactName: ConfigSnapShot
            PathtoPublish: '${{ variables.ServersBasePath }}'
            publishLocation: Container