name: $(Year:YYYY).$(Month).$(DayOfMonth).$(Rev:rr)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Server/*

parameters:
  - name: InstallRust
    type: boolean
    displayName: 'Install Rust'
    default: false
  - name: DeployConfig
    type: boolean
    displayName: Deploy Server / Mod Condif
    default: true
  - name: InstallUMod
    type: boolean
    displayName: 'Install uMod / Oxide'
    default: false
  - name: InstallMods
    type: boolean
    displayName: Install Mods
    default: true
  - name: FullClean
    displayName: Full Clean
    type: boolean
    default: false
  - name: Wipe
    displayName: Wipe Game Server
    type: boolean
    default: false
  - name: StopService
    displayName: Stop Game Server
    type: boolean
    default: false    
  - name: StartService
    type: boolean
    displayName: Start Game Server
    default: false
  - name: SkipClean
    type: boolean
    displayName: Skip Post Deployment Cleanup
    default: false


resources:
  repositories:
    - repository: Templates
      type: git
      name: OneBuild/OneBuild.Pipelines
      ref: refs/tags/0.stable
      endpoint: UTMO
  pipelines:
    - pipeline: latest
      source: TheRustyBear
      trigger:
        branches:
          include:
            - main

variables:
  dt: Pipelines/BaseInfra/Stages.Base.Template.yml@Templates

pool: PHX-Games

stages:
  - ${{ if or(eq(parameters.InstallRust, true),eq(parameters.DeployConfig, true))}}:
    - stage: S1
      displayName: Stage 1 (Deploy)
      dependsOn: []
      jobs:
        - deployment: d1
          environment: PHX
          displayName: Deploy Base Rust Game Server
          variables:
            - template: DeployVariables.variables.yml
          strategy:
            runOnce:
              preDeploy:
                steps:
                  - template: PreDeploy.Step.yml
                    parameters:
                      StopServer: ${{ parameters.StopService }}
                  - ${{ if or(eq(parameters.Wipe, true), eq(parameters.FullClean, true))}}:
                    - task: PowerShell@2
                      displayName: Clean Server
                      inputs:
                        targetType: filePath
                        filePath: ${{ variables.ScriptsBasePath }}/Clean-Oxide.ps1
                        arguments: '-ServerPath "${{ variables.ServerPath }}" -FullClean $${{ parameters.FullClean}}'
              deploy:
                steps:
                  - ${{ if eq(parameters.InstallRust, true)}}:
                    - task: PowerShell@2
                      displayName: 'Install / Update Rust Server'
                      inputs:
                        targetType: filePath
                        filePath: '${{ variables.ScriptsBasePath }}/Update-BaseRustServer.ps1'
                  - ${{ if eq(parameters.DeployConfig, true)}}:
                    - task: PowerShell@2
                      displayName: Publish Server Configuration Files
                      inputs:
                        targetType: filePath
                        filePath: ${{ variables.ScriptsBasePath }}/Install-ServerConfigs.ps1
                        arguments: -ServerPath '${{ variables.ServerPath }}' -ServerRepoPath '${{ variables.SourcesRoot }}'
  - ${{ if or(eq(parameters.InstallUMod, true),eq(parameters.InstallMods, true))}}:
    - stage: S2
      displayName: Stage 2 (MOD)
      dependsOn: S1
      jobs:
        - deployment: d2
          environment: PHX
          displayName: Deploy Oxide on to Rust Game Server
          variables:
            - template: DeployVariables.variables.yml
          strategy:
            runOnce:
              preDeploy:
                steps:
                  - template: PreDeploy.Step.yml
                    parameters:
                      StopServer: ${{ parameters.StopService }}
              deploy:
                steps:
                  - ${{ if eq(parameters.InstallUMod, true)}}:
                    - task: PowerShell@2
                      displayName: 'Install UMod'
                      inputs:
                        targetType: filePath
                        filePath: '${{ variables.ScriptsBasePath }}/Install-RustOxide.ps1'
                  - ${{ if eq(parameters.InstallMods, true)}}:
                    - task: PowerShell@2
                      displayName: Install Mods
                      inputs:
                        targetType: filePath
                        filePath: ${{ variables.ScriptsBasePath }}/Install-OxideMods.ps1
                        arguments: -ServerPath '${{ variables.ServerPath }}' -ResourcesPath '${{ variables.SourcesRoot }}'
  - stage: S3
    displayName: Stage 3 (CLEAN)
    dependsOn: 
      - ${{ if or(eq(parameters.InstallRust, true),eq(parameters.DeployConfig, true))}}:
        - S1
      - ${{ if or(eq(parameters.InstallUMod, true),eq(parameters.InstallMods, true))}}:
        - S2
    condition: always()
    jobs:
      - deployment: d3
        environment: PHX
        displayName: Post Deployment Activities
        variables:          
        - template: DeployVariables.variables.yml
        strategy:
          runOnce:
            deploy:
              steps:
                - ${{ if eq(parameters.StartService, true) }}:
                  - task: PowerShell@2
                    displayName: Start Rust Server
                    inputs:
                      targetType: inline
                      script: |
                        Start-Service -Name "RustUMod"
                - ${{ if eq(parameters.SkipClean, false) }}:
                  - task: PowerShell@2
                    displayName: Clean-up Deployment Files
                    condition: always() 
                    inputs:
                      targetType: inline
                      script: |
                        Write-Output "Removing Plugin Manifest"
                        Remove-Item -Path '${{ variables.ServerPath }}\oxide\plugins\plugins.manifest.json' -ErrorAction SilentlyContinue