# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: 

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Server/*

pool:
  name: 'PHX-Games'

parameters:
  - name: InstallRust
    type: boolean
    displayName: 'Install Rust'
    default: false
  - name: InstallUMod
    type: boolean
    displayName: 'Install uMod / Oxide'
    default: false

variables:
  ScriptsBasePath: '$(System.DefaultWorkingDirectory)/.scripts'
  ServersBasePath: '$(System.DefaultWorkingDirectory)/Server'

stages:
- stage:
  displayName: 'Snapshot Config & Deploy Latest Server Bits (Optional)'
  jobs:
    - job: CCS
      displayName: Capture Config Snapshot
      steps:
        - task: PublishBuildArtifacts@1
          displayName: Publish Configuration Snapshot As Build Artifact
          inputs:
            ArtifactName: ConfigSnapShot
            PathtoPublish: '${{ variables.ServersBasePath }}'
            publishLocation: Container
    - job: PDT
      displayName: Pre Deployment Tasks
      condition: or(eq(${{ parameters.InstallRust }}, true), eq(${{ parameters.InstallUMod }}, true))
      steps:
        - task: PowerShell@2
          displayName: 'Stop Rust Server'
          inputs:
            targetType: inline
            script: |
              $ServerServiceNames = @("RustUMod")
              $serviceRunning = Get-Service -name "RustUMod"
              if($serviceRunning.Status -eq 'Running')
              {
                $ServerServiceNames | %{ Stop-Service -Name $_}
              }
    - job: IBG
      displayName: Install Base Game
      condition: and(succeeded(), eq(${{ parameters.InstallRust }}, true))
      dependsOn: PDT
      steps:
        - task: PowerShell@2
          displayName: 'Install / Update Rust Server'
          inputs:
            targetType: filePath
            filePath: '${{ variables.ScriptsBasePath }}/Update-BaseRustServer.ps1'
    - job: IMP
      displayName: Install Mod Platform
      condition: and(succeeded(), eq(${{ parameters.InstallUMod }}, true))
      dependsOn: IBG
      steps:
        - task: PowerShell@2
          displayName: 'Install UMod'
          inputs:
            targetType: filePath
            filePath: '${{ variables.ScriptsBasePath }}/Install-RustOxide.ps1'